// Code generated by counterfeiter. DO NOT EDIT.
package commandsfakes

import (
	"sync"

	"github.com/pivotal-cf/pivnet-cli/commands"
)

type FakeCurlClient struct {
	MakeRequestStub        func(method string, body string, url string) error
	makeRequestMutex       sync.RWMutex
	makeRequestArgsForCall []struct {
		method string
		body   string
		url    string
	}
	makeRequestReturns struct {
		result1 error
	}
	makeRequestReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCurlClient) MakeRequest(method string, body string, url string) error {
	fake.makeRequestMutex.Lock()
	ret, specificReturn := fake.makeRequestReturnsOnCall[len(fake.makeRequestArgsForCall)]
	fake.makeRequestArgsForCall = append(fake.makeRequestArgsForCall, struct {
		method string
		body   string
		url    string
	}{method, body, url})
	fake.recordInvocation("MakeRequest", []interface{}{method, body, url})
	fake.makeRequestMutex.Unlock()
	if fake.MakeRequestStub != nil {
		return fake.MakeRequestStub(method, body, url)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.makeRequestReturns.result1
}

func (fake *FakeCurlClient) MakeRequestCallCount() int {
	fake.makeRequestMutex.RLock()
	defer fake.makeRequestMutex.RUnlock()
	return len(fake.makeRequestArgsForCall)
}

func (fake *FakeCurlClient) MakeRequestArgsForCall(i int) (string, string, string) {
	fake.makeRequestMutex.RLock()
	defer fake.makeRequestMutex.RUnlock()
	return fake.makeRequestArgsForCall[i].method, fake.makeRequestArgsForCall[i].body, fake.makeRequestArgsForCall[i].url
}

func (fake *FakeCurlClient) MakeRequestReturns(result1 error) {
	fake.MakeRequestStub = nil
	fake.makeRequestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCurlClient) MakeRequestReturnsOnCall(i int, result1 error) {
	fake.MakeRequestStub = nil
	if fake.makeRequestReturnsOnCall == nil {
		fake.makeRequestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.makeRequestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCurlClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.makeRequestMutex.RLock()
	defer fake.makeRequestMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCurlClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ commands.CurlClient = new(FakeCurlClient)
